Update recipe

diff --git a/net-irc/irssi/patches/irssi-0.8.17-haiku.patch b/net-irc/irssi/patches/irssi-0.8.17-haiku.patch
--- a/net-irc/irssi/patches/irssi-0.8.17-haiku.patch
+++ b/net-irc/irssi/patches/irssi-0.8.17-haiku.patch
@@ -313,3 +313,38 @@ index f148885..c534a3e 100644
  if test "x$ac_cv_prog_gcc" = "xyes"; then
 --
 2.2.2
+
+From cfff5e78aba54d0f881f212080c2beb7bc090bea Mon Sep 17 00:00:00 2001
+From: pisculichi <pisculichi@openmailbox.com>
+Date: Sun, 27 Mar 2016 15:04:26 +0000
+Subject: [PATCH] Add links to convert html -> text in autogen.sh
+
+---
+ autogen.sh | 6 ++++--
+ 1 file changed, 4 insertions(+), 2 deletions(-)
+
+diff --git a/autogen.sh b/autogen.sh
+index cf4b979..5409569 100755
+--- a/autogen.sh
++++ b/autogen.sh
+@@ -25,14 +25,16 @@ cat docs/help/in/Makefile.am.gen|sed "s/@HELPFILES@/$files/g"|sed 's/?/\\?/g'|tr
+ files=`echo $files|sed 's/\.in//g'`
+ cat docs/help/Makefile.am.gen|sed "s/@HELPFILES@/$files/g"|sed 's/?/\\?/g'|tr '!?' '\t\n' > docs/help/Makefile.am
+
+-# .html -> .txt with lynx or elinks
++# .html -> .txt with lynx, elinks or links
+ echo "Documentation: html -> txt..."
+ if type lynx >/dev/null 2>&1 ; then
+   lynx -dump -nolist docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
+ elif type elinks >/dev/null 2>&1 ; then
+   elinks -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
++elif type links >/dev/null 2>&1 ; then
++  links -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
+ else
+-  echo "**Error**: No lynx or elinks present"
++  echo "**Error**: No lynx, elinks or links present"
+   exit 1
+ fi
+
+--
+2.2.2
