ffmpeg: disable SSE and a few things for GCC2

diff --git a/media-video/ffmpeg/patches/ffmpeg-0.10-gcc2.patch b/media-video/ffmpeg/patches/ffmpeg-0.10-gcc2.patch
--- a/media-video/ffmpeg/patches/ffmpeg-0.10-gcc2.patch
+++ b/media-video/ffmpeg/patches/ffmpeg-0.10-gcc2.patch
@@ -209,3 +209,42 @@ index e1ba799..3820056 100644
          default:
              av_log(c, AV_LOG_ERROR, "unsupported planar RGB conversion %s -> %s\n",
                      av_get_pix_fmt_name(c->srcFormat), av_get_pix_fmt_name(c->dstFormat));
+diff --git a/configure b/configure 
+--- ffmpeg-0.10/configure       2012-01-26 22:15:59.035389440 +0000
++++ ffmpeg-0.10/configure       2012-03-20 00:55:05.090963968 +0000
+@@ -1359,7 +1359,6 @@
+ 
+ aligned_stack_if_any="ppc x86"
+ fast_64bit_if_any="alpha ia64 mips64 parisc64 ppc64 sparc64 x86_64"
+-fast_clz_if_any="alpha armv5te avr32 mips ppc x86"
+ fast_unaligned_if_any="armv6 ppc x86"
+ 
+ inline_asm_deps="!tms470"
+@@ -1948,6 +1947,7 @@
+ done
+ 
+ enable $ARCH_EXT_LIST $ALL_TESTS
++disable sse
+ 
+ die_unknown(){
+     echo "Unknown option \"$1\"."
+@@ -2831,10 +2831,6 @@
+ struct { int x; } __attribute__((packed)) x;
+ EOF
+ 
+-check_cc <<EOF && enable attribute_may_alias
+-union { int x; } __attribute__((may_alias)) x;
+-EOF
+-
+ check_cc <<EOF || die "endian test failed"
+ unsigned int endian = 'B' << 24 | 'I' << 16 | 'G' << 8 | 'E';
+ EOF
+@@ -3108,8 +3104,6 @@
+ enabled vaapi && require vaapi va/va.h vaInitialize -lva
+ 
+ check_mathfunc cbrtf
+-check_mathfunc exp2
+-check_mathfunc exp2f
+ check_mathfunc llrint
+ check_mathfunc llrintf
+ check_mathfunc log2
