cvs: fix rcs2log link path. Closes #103

diff --git a/dev-vcs/cvs/patches/cvs-1.12.13.1.patch b/dev-vcs/cvs/patches/cvs-1.12.13.1.patch
--- a/dev-vcs/cvs/patches/cvs-1.12.13.1.patch
+++ b/dev-vcs/cvs/patches/cvs-1.12.13.1.patch
@@ -224,3 +224,16 @@ diff -up cvs-1.12.13.1/src/wrapper.c.orig cvs-1.12.13.1/src/wrapper.c
      /* If we can't find a home directory, ignore ~/.cvswrappers.  This may
         make tracking down problems a bit of a pain, but on the other
         hand it might be obnoxious to complain when CVS will function
+diff --git a/contrib/Makefile.in b/contrib/Makefile.in
+index ed473e5..fccaa02 100644
+--- a/contrib/Makefile.in
++++ b/contrib/Makefile.in
+@@ -767,7 +767,7 @@ install-data-local:
+ 	    echo "test ! -f $(DESTDIR)$(bindir)/`echo $$p|sed '$(transform)'`"; \
+ 	    echo "  && cd $(DESTDIR)$(bindir) && $(LN_S) ../share/$(PACKAGE)/contrib/`echo $$p|sed '$(transform)'` ."; \
+ 	    (test ! -f $(DESTDIR)$(bindir)/`echo $$p|sed '$(transform)'` \
+-	        && cd $(DESTDIR)$(bindir) && $(LN_S) ../share/$(PACKAGE)/contrib/`echo $$p|sed '$(transform)'` .) \
++	        && cd $(DESTDIR)$(bindir) && $(LN_S) ${datarootdir}/$(PACKAGE)/contrib/`echo $$p|sed '$(transform)'` .) \
+ 	      || (echo "Link creation failed" && if test -f $$p; then \
+ 	           echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(bindir)/`echo $$p|sed '$(transform)'`"; \
+ 	           $(INSTALL_SCRIPT) $$p $(DESTDIR)$(bindir)/`echo $$p|sed '$(transform)'`; \
